services:
  server:
    container_name: mic-monitering-server
    build: .
    restart: unless-stopped
    ports:
      - "5005:5005"
    volumes:
      - ./data:/data

networks:
  default:
    external:
      name: sce