services:
  server:
    container_name: mic-monitering-server
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      sce:
        aliases:
          - mic-monitering-server.sce
          - mic-monitering-server
networks:
  sce:
    external: true
    name: sce